image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Publishing website'
  - mkdir -p public/
  - cp -rv app/ public/app/latest/
  - cp -rv website/publish/ public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

