image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'Publishing website'
  - mkdir -p public/
  - cp -rv website/publish/* public
  - mkdir -p public/app/
  - cp -rv app public/app/
  - mv public/app/app/ public/app/latest/
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

